CofeeApp.class: CoffeeMaker.java ElectricHeater.java Thermosiphon.java CoffeeApp.java Heater.java PumpModule.java DripCoffeeModule.java Pump.java
	javac -cp "../libs/dagger-compiler-1.2.1.jar:../libs/dagger-1.2.1.jar:../libs/javax.inject-1.jar:../libs/javawriter-2.5.0.jar" CoffeeMaker.java ElectricHeater.java Thermosiphon.java CoffeeApp.java Heater.java PumpModule.java DripCoffeeModule.java Pump.java

clean:
	rm *.class

run:
	java -cp ".:../libs/dagger-compiler-1.2.1.jar:../libs/dagger-1.2.1.jar:../libs/javax.inject-1.jar:../libs/javawriter-2.5.0.jar" CoffeeApp
